# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72621fede0cb56ca24334caf7eddf16987241f561c63aac992221de331cfd18480b4f7df15abbb10796d5bb0ea5956a998121bfea6d982d4ce0e4c4540f8bcc3

test:
  secret_key_base: d679db72f83feb26ce825652f83bf11cb86f03095b236964568be0fabe8909967ccbab550ec3fd61a48755a705a7b8c3c597cad811db9aa003754ee533f773b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
